# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{super_crud}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Paul Narowski"]
  s.date = %q{2010-01-25}
  s.description = %q{This is a admin system abstraction to get you up and running faster}
  s.email = %q{jnarowski@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/super_crud.rb",
     "lib/super_crud/controller.rb",
     "lib/super_crud/helper.rb",
     "lib/super_crud/model.rb",
     "test/helper.rb"
  ]
  s.homepage = %q{http://github.com/jnarowski/super_crud}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Abstracts some helper model and controller logic}
  s.test_files = [
    "test/helper.rb",
     "test/test_super_crud.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

